# Generated by Django 6.0.3 on 2026-03-26 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Rareza',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaIngreso',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
    ]
