# Generated by Django 6.0.3 on 2026-03-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_producto_rareza_producto_fechaingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Productos'),
        ),
    ]
