# Generated by Django 6.0.3 on 2026-03-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='Productos'),
        ),
    ]
